### ISSUE TITLE
Workers throwing SQLException when crawling

### ISSUE THREAD

**Issue by earthquakesan** [dice-group/Squirrel#18]
```
worker1      | java.sql.SQLException: invalid cursor state: identified cursor is not open
worker1      | 	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
worker1      | 	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
worker1      | 	at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source)
worker1      | 	at org.hsqldb.jdbc.JDBCResultSet.checkClosed(Unknown Source)
worker1      | 	at org.hsqldb.jdbc.JDBCResultSet.next(Unknown Source)
worker1      | 	at org.aksw.simba.squirrel.sink.collect.SqlBasedUriCollector$ResultIterator.moveForward(SqlBasedUriCollector.java:176)
worker1      | 	at org.aksw.simba.squirrel.sink.collect.SqlBasedUriCollector$ResultIterator.hasNext(SqlBasedUriCollector.java:148)
worker1      | 	at org.aksw.simba.squirrel.worker.impl.WorkerImpl.sendNewUris(WorkerImpl.java:139)
worker1      | 	at org.aksw.simba.squirrel.worker.impl.WorkerImpl.performCrawling(WorkerImpl.java:123)
worker1      | 	at org.aksw.simba.squirrel.worker.impl.WorkerImpl.crawl(WorkerImpl.java:95)
worker1      | 	at org.aksw.simba.squirrel.worker.impl.WorkerImpl.run(WorkerImpl.java:80)
worker1      | 	at org.aksw.simba.squirrel.components.WorkerComponent.run(WorkerComponent.java:71)
worker1      | 	at org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:67)
worker1      | Caused by: org.hsqldb.HsqlException: invalid cursor state: identified cursor is not open
worker1      | 	at org.hsqldb.error.Error.error(Unknown Source)
worker1      | 	at org.hsqldb.error.Error.error(Unknown Source)
worker1      | 	... 11 more
```

**Comment by MichaelRoeder** [comment]
This issue remains as it can be seen from https://github.com/dice-group/Squirrel/blob/master/crash_logs/run_2/worker2.log.json#L45 on.

Note that the worker does not seem to get out of this state. It still requests new URIs from the frontier and crawls them. However, as soon as it tries to send data back to the frontier (the URIs stored in the database), it throws the exception above.
