### ISSUE TITLE
Improve error reporting for component starter

### ISSUE THREAD

**Issue by earthquakesan** [dice-group/Squirrel#39]
When I am running worker, I see this error in the logs:
```
2017-12-05 11:18:39,444 [main] ERROR [o.h.c.r.ComponentStarter      ] - <Exception while executing component. Exiting with error code.>
java.lang.NullPointerException
	at org.aksw.simba.squirrel.components.WorkerComponent.init(WorkerComponent.java:61)
	at org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:65)
```

**Comment by MichaelRoeder** [comment]
This is a known bug. It has been solved in the `develop` branch.

**Comment by MichaelRoeder** [comment]
Improving the error reporting is not necessary in this case since it is a simple programming error that should not occur in practice :wink:

**Comment by earthquakesan** [comment]
it is indeed is not in develop branch, I will close it %)
