### ISSUE TITLE
DUMP files are downloaded with FTP fetcher (wrong protocol?)

### ISSUE THREAD

**Issue by earthquakesan** [dice-group/Squirrel#40]
Both seed URIs are failing atm:
```
worker3_1    | 2017-12-05 12:34:42,885 [main] ERROR [o.a.s.s.f.f.FTPFetcher        ] - <Exception while trying to download (http://danbri.org/foaf.rdf). Returning null.>
worker3_1    | java.net.ConnectException: Connection timed out (Connection timed out)
worker3_1    | 	at java.net.PlainSocketImpl.socketConnect(Native Method)
worker3_1    | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
worker3_1    | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
worker3_1    | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
worker3_1    | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
worker3_1    | 	at java.net.Socket.connect(Socket.java:589)
worker3_1    | 	at org.apache.commons.net.SocketClient._connect(SocketClient.java:243)
worker3_1    | 	at org.apache.commons.net.SocketClient.connect(SocketClient.java:181)
worker3_1    | 	at org.apache.commons.net.SocketClient.connect(SocketClient.java:287)
worker3_1    | 	at org.aksw.simba.squirrel.fetcher.ftp.FTPFetcher.requestData(FTPFetcher.java:57)
worker3_1    | 	at org.aksw.simba.squirrel.fetcher.ftp.FTPFetcher.fetch(FTPFetcher.java:49)
worker3_1    | 	at org.aksw.simba.squirrel.fetcher.manage.SimpleOrderedFetcherManager.fetch(SimpleOrderedFetcherManager.java:45)
worker3_1    | 	at org.aksw.simba.squirrel.worker.impl.WorkerImpl.performCrawling(WorkerImpl.java:133)
worker3_1    | 	at org.aksw.simba.squirrel.worker.impl.WorkerImpl.crawl(WorkerImpl.java:111)
worker3_1    | 	at org.aksw.simba.squirrel.worker.impl.WorkerImpl.run(WorkerImpl.java:96)
worker3_1    | 	at org.aksw.simba.squirrel.components.WorkerComponent.run(WorkerComponent.java:72)
worker3_1    | 	at org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:67)
```

```
worker3_1    | 2017-12-05 12:32:35,389 [main] ERROR [o.a.s.s.f.f.FTPFetcher        ] - <Exception while trying to download (http://dbpedia.org/resource/New_York). Returning null.>
worker3_1    | java.net.NoRouteToHostException: No route to host (Host unreachable)
worker3_1    | 	at java.net.PlainSocketImpl.socketConnect(Native Method)
worker3_1    | 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
worker3_1    | 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
worker3_1    | 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
worker3_1    | 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
worker3_1    | 	at java.net.Socket.connect(Socket.java:589)
worker3_1    | 	at org.apache.commons.net.SocketClient._connect(SocketClient.java:243)
worker3_1    | 	at org.apache.commons.net.SocketClient.connect(SocketClient.java:181)
worker3_1    | 	at org.apache.commons.net.SocketClient.connect(SocketClient.java:287)
worker3_1    | 	at org.aksw.simba.squirrel.fetcher.ftp.FTPFetcher.requestData(FTPFetcher.java:57)
worker3_1    | 	at org.aksw.simba.squirrel.fetcher.ftp.FTPFetcher.fetch(FTPFetcher.java:49)
worker3_1    | 	at org.aksw.simba.squirrel.fetcher.manage.SimpleOrderedFetcherManager.fetch(SimpleOrderedFetcherManager.java:45)
worker3_1    | 	at org.aksw.simba.squirrel.worker.impl.WorkerImpl.performCrawling(WorkerImpl.java:133)
worker3_1    | 	at org.aksw.simba.squirrel.worker.impl.WorkerImpl.crawl(WorkerImpl.java:111)
worker3_1    | 	at org.aksw.simba.squirrel.worker.impl.WorkerImpl.run(WorkerImpl.java:96)
worker3_1    | 	at org.aksw.simba.squirrel.components.WorkerComponent.run(WorkerComponent.java:72)
worker3_1    | 	at org.hobbit.core.run.ComponentStarter.main(ComponentStarter.java:67)
```

**Comment by MichaelRoeder** [comment]
Should not be possible anymore, since the fetchers check for the correct URI scheme: https://github.com/dice-group/Squirrel/blob/master/src/main/java/org/aksw/simba/squirrel/fetcher/ftp/FTPFetcher.java#L38

**Comment by earthquakesan** [comment]
Does not work, see test case here:

https://github.com/dice-group/Squirrel/blob/develop/src/test/java/org/aksw/simba/squirrel/fetcher/ftp/FTPFetcherTest.java
