### ISSUE TITLE
Frontier Error: Uncatched throwable when processing an incoming message in the RPCServer.

### ISSUE THREAD

**Issue by ajrox090** [dice-group/Squirrel#87]
Stack trace:

`
com.mongodb.MongoCommandException: Command failed with error 11600: 'interrupted at shutdown' on server mongodb:27017. The full response is { "ok" : 0.0, "errmsg" : "interrupted at shutdown", "code" : 11600, "codeName" : "InterruptedAtShutdown" }`

	`at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java :164)
	at com.mongodb.connection.InternalStreamConnection.receiveCommandMessageResponse(InternalStreamConnection.java:295)
	at com.mongodb.connection.InternalStreamConnection.sendAndReceive(InternalStreamConnection.java:255)
	at com.mongodb.connection.CommandHelper.sendAndReceive(CommandHelper.java:84)
	at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:39)
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.lookupServerDescription(DefaultServerMonitor.java:177)
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:121)
	at java.lang.Thread.run(Thread.java:748)`
`2018-12-08 19:35:15,002 [pool-4-thread-7] ERROR [o.h.c.r.DataReceiverImpl      ] - 
<Uncatched throwable when processing an incoming message in the RPCServer.>`

**Comment by gsjunior86** [comment]
@ajrox090 , can you describe more the situation that this happened?

**Comment by ajrox090** [comment]
The crawler was run for 10 hours and  was manually terminated to analyse the logs, do you think this issue is because of manual termination? There is no trace of this error anywhere else in the logs but only in towards the end.

**Comment by gsjunior86** [comment]
@ajrox090 , this is probably the cause
