### ISSUE TITLE
Out of memory error : Worker2

### ISSUE THREAD

**Issue by ajrox090** [dice-group/Squirrel#93]
* Worker2 terminated with following error in VM after approximately 2 days of runtime,
```
2018-12-13 04:58:06,028 [main] ERROR [o.d.s.c.WorkerComponentStarter] - <Exception while executing component. Exiting with error code.>
java.lang.OutOfMemoryError: GC overhead limit exceeded
        at java.util.Arrays.copyOf(Arrays.java:3236)
        at java.util.zip.ZipCoder.getBytes(ZipCoder.java:89)
        at java.util.zip.ZipFile.getEntry(ZipFile.java:316)
        at java.util.jar.JarFile.getEntry(JarFile.java:240)
        at java.util.jar.JarFile.getJarEntry(JarFile.java:223)
        at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:1042)
        at sun.misc.URLClassPath$JarLoader.findResource(URLClassPath.java:1020)
        at sun.misc.URLClassPath$1.next(URLClassPath.java:267)
        at sun.misc.URLClassPath$1.hasMoreElements(URLClassPath.java:277)
        at java.net.URLClassLoader$3$1.run(URLClassLoader.java:601)
        at java.net.URLClassLoader$3$1.run(URLClassLoader.java:599)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader$3.next(URLClassLoader.java:598)
        at java.net.URLClassLoader$3.hasMoreElements(URLClassLoader.java:623)
        at sun.misc.CompoundEnumeration.next(CompoundEnumeration.java:45)
        at sun.misc.CompoundEnumeration.hasMoreElements(CompoundEnumeration.java:54)
        at sun.misc.CompoundEnumeration.next(CompoundEnumeration.java:45)
        at sun.misc.CompoundEnumeration.hasMoreElements(CompoundEnumeration.java:54)
        at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:354)
        at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
        at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
        at javax.xml.parsers.FactoryFinder$1.run(FactoryFinder.java:293)
        at java.security.AccessController.doPrivileged(Native Method)
        at javax.xml.parsers.FactoryFinder.findServiceProvider(FactoryFinder.java:289)
        at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:267)
        at javax.xml.parsers.SAXParserFactory.newInstance(SAXParserFactory.java:127)
        at org.apache.tika.detect.XmlRootExtractor.extractRootElement(XmlRootExtractor.java:51)
        at org.apache.tika.detect.XmlRootExtractor.extractRootElement(XmlRootExtractor.java:42)
        at org.apache.tika.mime.MimeTypes.getMimeType(MimeTypes.java:212)
        at org.apache.tika.mime.MimeTypes.detect(MimeTypes.java:494)
        at org.apache.tika.detect.CompositeDetector.detect(CompositeDetector.java:84)
        at org.apache.tika.Tika.detect(Tika.java:158)
2018-12-13 04:58:06,803 [main] INFO  [ileSystemXmlApplicationContext] - <Closing org.springframework.context.support.FileSystemXmlApplicationContext@5577140b: startup date [Tue Dec 11 17:21:05 UTC 2018]; root of context hierarchy>
2018-12-13 04:58:06,860 [main] ERROR [o.d.s.s.i.f.FileBasedSink     ] - <Should close the sink for the URI "http://w3id.org/squirrel/metadata" but couldn't find it.>
2018-12-13 04:58:07,005 [main] ERROR [o.d.s.s.i.f.FileBasedSink     ] - <Should close the sink for the URI "http://w3id.org/squirrel/metadata" but couldn't find it.>
```

**Comment by gsjunior86** [comment]
@ajrox090 , what is the resources available ?

**Comment by gsjunior86** [comment]
This seems a low specs problem. Closing it.
